name: CI/CD Production

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy_prod:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      # ✅ 1️⃣ Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ 2️⃣ Setup Node.js
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      # ✅ 3️⃣ Cài đặt dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # ✅ 4️⃣ Tạo file `.env`
      - name: Create .env file
        run: echo "${{ secrets.ENV_CONTENT }}" > .env

      # ✅ 5️⃣ Build và push Docker Image
      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/my-app:latest
          build-args: |
            ENV_FILE=.env

      # ✅ 6️⃣ Deploy lên Production Server
      - name: Deploy to Production Server
        run: echo "Deploying to Production Server..."
