name: CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      # ✅ 1️⃣ Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ 2️⃣ Setup Node.js và cache dependencies
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Create .env file
          run: echo "${{ secrets.ENV_CONTENT }}" > .env
